# Generated by Django 5.2.4 on 2026-04-03 02:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='game_of_feeds/default_profile_idzhze', max_length=255, verbose_name='image'),
        ),
    ]
