# Generated by Django 5.2.4 on 2026-04-03 02:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='default_profile_idzhze', max_length=255, verbose_name='image'),
        ),
    ]
